name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        run: curl -L https://foundry.paradigm.xyz | bash && foundryup
      - name: Run Foundry Tests
        run: cd contracts && forge test
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: { node-version: '18' }
      - name: Install Frontend Dependencies
        run: cd frontend && npm install
      - name: Build Frontend
        run: cd frontend && npm run build
